name = "FiMC Vanilla+"
author = "filcuk"
version = "1.0.0-rc.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "570dc41cd2946f57dca927a0f3eb84b1cec48d98077a16bcd47ff25c06b6830e"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
