# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				arrow = true
				donkey = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				pig = true
				slime = true
				allay = true
				pillager = true
				iron_golem = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				cat = true
				rabbit = true
				zombie = true
				firework_rocket = true
				drowned = true
				guardian = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				turtle = true
				villager = true
				wolf = true
				salmon = true
				zombie_villager = true
				elder_guardian = true
				goat = true
				ocelot = true
				horse = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.halfdoors]
				door_saw = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.supplementaries]
				rope_arrow = true

			[light_sources.settings.entities.tumbleweed]
				tumbleweed = true

